version: '3.8'

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    volumes:
      - ./sessions:/app/sessions
    env_file:
      - ./.env 
    environment:
      - SESSION_PATH=/app/sessions
    networks:
      - shared_network
    restart: unless-stopped
    ports:
      - "3123:3000"    # Expose port 3000
networks:
  shared_network:
    external: true

